// SPDX-License-Identifier: MIT OR GPL-2.0-only
//! Reed-Solomon erasure coding over GF(2^8), wfb-ng's `WFB_FEC_VDM_RS`.
//!
//! A Rust implementation of the systematic Vandermonde code that zfec
//! implements and wfb-ng links: the same field, the same generator matrix,
//! and therefore the same parity bytes.
//!
//! Credit where it is due. The algorithm is Luigi Rizzo's `fec` (1997, BSD),
//! by way of zfec (Zooko Wilcox-O'Hearn / Allmydata, GPL-2.0-or-later). What
//! follows is an independent implementation of it, not a translation, but it
//! is their code that defines what "correct" means here and `tests/wfb.rs`
//! checks this against vectors generated by it.
//!
//! Only the decode side is needed to receive, but encode is here too: it is
//! four lines given the matrix, and without it the round-trip test that gives
//! any confidence in the decode side could not be written.

/// The field is GF(2^8) modulo x^8 + x^4 + x^3 + x^2 + 1.
///
/// Rizzo's code spells this as the string "101110001" and derives the tables
/// from it; the constant is the same polynomial written the usual way.
const PRIMITIVE: u16 = 0x11d;

/// Logarithm and exponent tables for the field.
///
/// `exp` is doubled so a sum of two logarithms (each at most 254) indexes it
/// without a reduction step.
struct Field {
    exp: [u8; 510],
    log: [u8; 256],
}

impl Field {
    fn new() -> Self {
        let mut exp = [0u8; 510];
        let mut log = [0u8; 256];

        let mut x: u16 = 1;
        for (i, slot) in exp[..255].iter_mut().enumerate() {
            *slot = x as u8;
            log[x as usize] = i as u8;
            x <<= 1;
            if x & 0x100 != 0 {
                x ^= PRIMITIVE;
            }
        }
        // The second copy, so exp[log[a] + log[b]] never needs a modulo.
        let (first, second) = exp.split_at_mut(255);
        second.copy_from_slice(first);
        // log(0) is undefined; zfec parks it at 255 and guards every use.
        log[0] = 255;

        Self { exp, log }
    }

    fn mul(&self, a: u8, b: u8) -> u8 {
        if a == 0 || b == 0 {
            return 0;
        }
        self.exp[self.log[a as usize] as usize + self.log[b as usize] as usize]
    }

    fn inv(&self, a: u8) -> u8 {
        debug_assert!(a != 0, "0 has no inverse in the field");
        self.exp[255 - self.log[a as usize] as usize]
    }

    /// The 256-byte table of `c * x` for one fixed `c`.
    ///
    /// The bulk row operations multiply a whole block by a single constant,
    /// and a table lookup per byte is what makes that fast enough to run on
    /// every recovered fragment.
    fn mul_table(&self, c: u8) -> [u8; 256] {
        let mut table = [0u8; 256];
        for (x, slot) in table.iter_mut().enumerate() {
            *slot = self.mul(c, x as u8);
        }
        table
    }

    /// `dst += c * src`, the inner loop of both encode and decode.
    fn addmul(&self, dst: &mut [u8], src: &[u8], c: u8) {
        if c == 0 {
            return;
        }
        let table = self.mul_table(c);
        for (d, s) in dst.iter_mut().zip(src) {
            *d ^= table[*s as usize];
        }
    }
}

fn field() -> &'static Field {
    static FIELD: std::sync::OnceLock<Field> = std::sync::OnceLock::new();
    FIELD.get_or_init(Field::new)
}

/// A `(k, n)` code: `k` data fragments in, `n - k` parity fragments out.
pub struct Fec {
    k: usize,
    n: usize,
    /// The `n * k` systematic generator matrix, row-major. The top `k` rows
    /// are the identity - which is what "systematic" means, and why a block
    /// that arrives complete needs no arithmetic at all.
    enc: Vec<u8>,
}

/// What can go wrong recovering a block.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FecError {
    /// Fewer than `k` fragments, or a duplicate fragment number: the code
    /// needs exactly `k` distinct ones.
    NotEnoughFragments,
    /// A fragment number at or beyond `n`.
    BadFragmentIndex,
    /// The `k` fragments are linearly dependent. A Vandermonde matrix makes
    /// this impossible for distinct indices, so it means the indices lied.
    Singular,
}

impl std::fmt::Display for FecError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let text = match self {
            Self::NotEnoughFragments => "not enough distinct fragments to recover the block",
            Self::BadFragmentIndex => "fragment index outside the code",
            Self::Singular => "the fragments given are not independent",
        };
        f.write_str(text)
    }
}

impl Fec {
    /// Build the code for `k` of `n`. `None` for parameters outside the field.
    pub fn new(k: usize, n: usize) -> Option<Self> {
        if k < 1 || n < k || n > 255 {
            return None;
        }

        let f = field();

        // Start from the Vandermonde matrix v[row][col] = alpha^(row*col),
        // with the first row special-cased because alpha^0 = 1 for every
        // column would not give an invertible top block.
        let mut vdm = vec![0u8; n * k];
        vdm[0] = 1;
        for row in 0..n - 1 {
            for col in 0..k {
                vdm[(row + 1) * k + col] = f.exp[(row * col) % 255];
            }
        }

        // Invert the top k*k block and multiply the bottom rows by it. That
        // turns the top into the identity, so the data fragments travel as
        // themselves and only the parity rows cost anything.
        let top = invert_vandermonde(&vdm[..k * k], k)?;

        let mut enc = vec![0u8; n * k];
        for col in 0..k {
            enc[col * k + col] = 1;
        }
        for row in k..n {
            for col in 0..k {
                let mut acc = 0u8;
                for i in 0..k {
                    acc ^= f.mul(vdm[row * k + i], top[i * k + col]);
                }
                enc[row * k + col] = acc;
            }
        }

        Some(Self { k, n, enc })
    }

    pub fn k(&self) -> usize {
        self.k
    }

    pub fn n(&self) -> usize {
        self.n
    }

    /// Produce the `n - k` parity fragments for a block of `k` data fragments.
    ///
    /// Every fragment, data and parity alike, is `size` bytes; a short data
    /// fragment is zero-padded by the caller, which is what lets a block hold
    /// packets of different lengths.
    pub fn encode(&self, data: &[&[u8]], size: usize) -> Vec<Vec<u8>> {
        assert_eq!(data.len(), self.k, "a block is exactly k data fragments");
        let f = field();
        let mut parity = Vec::with_capacity(self.n - self.k);

        for row in self.k..self.n {
            let mut out = vec![0u8; size];
            for (col, block) in data.iter().enumerate() {
                let padded = &block[..block.len().min(size)];
                f.addmul(
                    &mut out[..padded.len()],
                    padded,
                    self.enc[row * self.k + col],
                );
            }
            parity.push(out);
        }
        parity
    }

    /// Recover the missing data fragments of a block.
    ///
    /// `have` is exactly `k` fragments and `index[i]` is the fragment number
    /// of `have[i]`. A data fragment that is present must be at its own
    /// position - `index[i] == i` - which is how the caller says which of the
    /// `k` are missing; the rest of the positions are filled with parity.
    ///
    /// Returns the recovered data fragments in ascending fragment order, each
    /// `size` bytes.
    pub fn decode(
        &self,
        have: &[&[u8]],
        index: &[usize],
        size: usize,
    ) -> Result<Vec<Vec<u8>>, FecError> {
        if have.len() != self.k || index.len() != self.k {
            return Err(FecError::NotEnoughFragments);
        }
        if index.iter().any(|i| *i >= self.n) {
            return Err(FecError::BadFragmentIndex);
        }
        for (row, i) in index.iter().enumerate() {
            if *i < self.k && *i != row {
                return Err(FecError::BadFragmentIndex);
            }
        }

        // Nothing to do when all k data fragments are present, which is the
        // overwhelmingly common case and worth not building a matrix for.
        if index.iter().enumerate().all(|(row, i)| *i == row) {
            return Ok(Vec::new());
        }

        // The rows of the generator matrix that produced the fragments we
        // actually have; inverting them undoes the encoding.
        let mut m = vec![0u8; self.k * self.k];
        for (row, &i) in index.iter().enumerate() {
            if i < self.k {
                m[row * self.k + i] = 1;
            } else {
                m[row * self.k..(row + 1) * self.k]
                    .copy_from_slice(&self.enc[i * self.k..(i + 1) * self.k]);
            }
        }
        let dec = invert(&mut m, self.k).ok_or(FecError::Singular)?;

        let f = field();
        let mut recovered = Vec::new();
        for (row, &i) in index.iter().enumerate() {
            if i < self.k {
                continue;
            }
            let mut out = vec![0u8; size];
            for (col, block) in have.iter().enumerate() {
                let padded = &block[..block.len().min(size)];
                f.addmul(&mut out[..padded.len()], padded, dec[row * self.k + col]);
            }
            recovered.push(out);
        }
        Ok(recovered)
    }
}

/// Invert the top-left `k * k` block of a Vandermonde matrix.
///
/// The general inverse below would do, but at O(k^3) with a matrix that is
/// rebuilt whenever a session key changes; the Vandermonde structure gives it
/// in O(k^2) by polynomial division, which is Rizzo's trick.
fn invert_vandermonde(src: &[u8], k: usize) -> Option<Vec<u8>> {
    let f = field();
    if k == 1 {
        // The one-element matrix is [1], which is its own inverse.
        return Some(vec![1]);
    }

    // The evaluation points, which are column 1 of the matrix.
    let p: Vec<u8> = (0..k).map(|i| src[i * k + 1]).collect();

    // Coefficients of P(x) = prod(x - p_i), built up one root at a time.
    // Subtraction is exclusive-or here, so the signs in the textbook version
    // all disappear.
    let mut c = vec![0u8; k];
    c[k - 1] = p[0];
    for (i, &p_i) in p.iter().enumerate().skip(1) {
        for j in k - i..k - 1 {
            c[j] ^= f.mul(p_i, c[j + 1]);
        }
        c[k - 1] ^= p_i;
    }

    let mut out = vec![0u8; k * k];
    let mut b = vec![0u8; k];
    for row in 0..k {
        // Synthetic division of P(x) by (x - p_row), whose quotient is the
        // Lagrange basis polynomial for this row, and whose value at p_row
        // normalizes it.
        let xx = p[row];
        let mut t = 1u8;
        b[k - 1] = 1;
        for i in (1..k).rev() {
            b[i - 1] = c[i] ^ f.mul(xx, b[i]);
            t = f.mul(xx, t) ^ b[i - 1];
        }
        if t == 0 {
            return None;
        }
        let t_inv = f.inv(t);
        for col in 0..k {
            out[col * k + row] = f.mul(t_inv, b[col]);
        }
    }
    Some(out)
}

/// Gauss-Jordan inverse of a general `k * k` matrix, or `None` if singular.
fn invert(m: &mut [u8], k: usize) -> Option<Vec<u8>> {
    let f = field();
    let mut inv = vec![0u8; k * k];
    for i in 0..k {
        inv[i * k + i] = 1;
    }

    for col in 0..k {
        // Any nonzero entry will do as a pivot; the field has no notion of a
        // numerically better one.
        let pivot = (col..k).find(|&row| m[row * k + col] != 0)?;
        if pivot != col {
            for j in 0..k {
                m.swap(pivot * k + j, col * k + j);
                inv.swap(pivot * k + j, col * k + j);
            }
        }

        let scale = f.inv(m[col * k + col]);
        for j in 0..k {
            m[col * k + j] = f.mul(m[col * k + j], scale);
            inv[col * k + j] = f.mul(inv[col * k + j], scale);
        }

        for row in 0..k {
            if row == col {
                continue;
            }
            let factor = m[row * k + col];
            if factor == 0 {
                continue;
            }
            for j in 0..k {
                m[row * k + j] ^= f.mul(factor, m[col * k + j]);
                inv[row * k + j] ^= f.mul(factor, inv[col * k + j]);
            }
        }
    }
    Some(inv)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_field_is_the_one_the_protocol_uses() {
        let f = field();
        // alpha^8 folds back through the primitive polynomial.
        assert_eq!(f.exp[8], 0x1d);
        assert_eq!(f.exp[0], 1);
        assert_eq!(f.exp[254], f.inv(f.exp[1]));
        // Multiplication is closed, commutative and has 1 as its identity.
        for a in 0..=255u8 {
            assert_eq!(f.mul(a, 1), a);
            assert_eq!(f.mul(a, 0), 0);
            assert_eq!(f.mul(a, 7), f.mul(7, a));
            if a != 0 {
                assert_eq!(f.mul(a, f.inv(a)), 1);
            }
        }
    }

    #[test]
    fn the_generator_matrix_is_systematic() {
        let fec = Fec::new(4, 8).unwrap();
        for row in 0..4 {
            for col in 0..4 {
                let expected = u8::from(row == col);
                assert_eq!(fec.enc[row * 4 + col], expected, "row {row} col {col}");
            }
        }
    }

    /// Fragments of ascending length, the shape a real block has: the parity
    /// is as long as the longest packet in the block and the rest are padded.
    fn block(k: usize, size: usize) -> Vec<Vec<u8>> {
        (0..k)
            .map(|i| {
                let mut frag = vec![0u8; size];
                for (j, b) in frag.iter_mut().enumerate() {
                    *b = ((i * 31 + j * 17 + 5) % 251) as u8;
                }
                frag
            })
            .collect()
    }

    /// Encode, drop `lost` data fragments, and check they come back.
    fn round_trip(k: usize, n: usize, lost: &[usize], size: usize) {
        let fec = Fec::new(k, n).unwrap();
        let data = block(k, size);
        let refs: Vec<&[u8]> = data.iter().map(|v| v.as_slice()).collect();
        let parity = fec.encode(&refs, size);

        let mut have: Vec<&[u8]> = Vec::new();
        let mut index: Vec<usize> = Vec::new();
        let mut spare = k;
        for (i, fragment) in data.iter().enumerate() {
            if lost.contains(&i) {
                // Fill the hole with the next parity fragment, exactly as the
                // aggregator does.
                have.push(&parity[spare - k]);
                index.push(spare);
                spare += 1;
            } else {
                have.push(fragment);
                index.push(i);
            }
        }

        let recovered = fec.decode(&have, &index, size).unwrap();
        assert_eq!(recovered.len(), lost.len());
        for (out, &i) in recovered.iter().zip(lost) {
            assert_eq!(out, &data[i], "fragment {i} of ({k},{n})");
        }
    }

    #[test]
    fn a_complete_block_needs_no_recovery() {
        let fec = Fec::new(8, 12).unwrap();
        let data = block(8, 64);
        let refs: Vec<&[u8]> = data.iter().map(|v| v.as_slice()).collect();
        fec.encode(&refs, 64);
        let index: Vec<usize> = (0..8).collect();
        assert!(fec.decode(&refs, &index, 64).unwrap().is_empty());
    }

    #[test]
    fn any_single_loss_is_recoverable() {
        for lost in 0..8 {
            round_trip(8, 12, &[lost], 137);
        }
    }

    #[test]
    fn losing_every_parity_fragments_worth_is_recoverable() {
        // 8 of 12 tolerates exactly four losses, which is the interesting
        // edge: one more and the block is gone.
        round_trip(8, 12, &[0, 1, 2, 3], 512);
        round_trip(8, 12, &[0, 3, 5, 7], 512);
        round_trip(8, 12, &[4, 5, 6, 7], 1400);
    }

    #[test]
    fn the_degenerate_codes_work() {
        // k = 1 is pure repetition, and n = k is no parity at all.
        round_trip(1, 4, &[0], 32);
        let fec = Fec::new(3, 3).unwrap();
        let data = block(3, 16);
        let refs: Vec<&[u8]> = data.iter().map(|v| v.as_slice()).collect();
        assert!(fec.encode(&refs, 16).is_empty());
    }

    #[test]
    fn impossible_parameters_are_rejected() {
        assert!(Fec::new(0, 4).is_none());
        assert!(Fec::new(5, 4).is_none());
        assert!(Fec::new(4, 256).is_none());
        assert!(Fec::new(255, 255).is_some());
    }

    #[test]
    fn a_short_or_repeated_fragment_set_is_refused() {
        let fec = Fec::new(4, 8).unwrap();
        let data = block(4, 32);
        let refs: Vec<&[u8]> = data.iter().map(|v| v.as_slice()).collect();
        assert_eq!(
            fec.decode(&refs[..3], &[0, 1, 2], 32),
            Err(FecError::NotEnoughFragments)
        );
        // A data fragment claimed to be at someone else's position.
        assert_eq!(
            fec.decode(&refs, &[1, 1, 2, 3], 32),
            Err(FecError::BadFragmentIndex)
        );
        assert_eq!(
            fec.decode(&refs, &[0, 1, 2, 99], 32),
            Err(FecError::BadFragmentIndex)
        );
    }
}
